version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend