version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    networks:
      - environment

networks:
  environment:
    external: true