version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - environment

networks:
  environment:
    external: true