version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    networks:
      - environment

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    networks:
      - environment

networks:
  environment:
    external: true